package views;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import utils.UtileriasStyle;
import utils.modelo.ImagenCelda;
import utils.modelo.ModeloTabla;

/**
 * Descipción: Interfaz para Administración de Catálogo de Criterios de Evaluación
 * @author PLUS-Juampa (Juan Paulino Cruz Mejía) GSI1333
 * @author juampa249@gmail.com
 * version: 1.1
 */
public class ViewAdministracionCriteriosEvaluacion extends javax.swing.JFrame {
    //Encabezado de columnas 
    private String[] encabezadoColumnas = {"Nombre","Estado","Eliminar"};
    //Definiendo el modelo de la tabla
    private DefaultTableModel modelo = new DefaultTableModel(null, encabezadoColumnas);
    
    /**
     * Creates new form ViewAdministracionDeCatalogoDeCriteriosDeEvaluacion
     * Vista que mostrará todos los componentes
     */
    public ViewAdministracionCriteriosEvaluacion() {
        initComponents();   // Inicia todo los componentes de la vista
        UtileriasStyle.centrarVentana(this);    // Centra la ventana dependiendo de la resolución de la pantalla
        UtileriasStyle.initStyle(panelCriteriosEvaluacion.getComponents()); // Inicia componentes de estilo predeterminados
        UtileriasStyle.initStyle(panelTitulo.getComponents());  // Inicia componentes de estilo predeterminados
        tableCriteriosEvaluacion.setModel(modelo);  // Inicia modelo default para la tabla de la vista
        txtNombre.requestFocus();
        this.iniTabla();
    }
    /**
     * Método para iniciar un modelo especial para la tabla y que muestre las imagen para eliminar
     * y posteriormente que mande un mensaje de qué registro ha sido eliminado
     */
    private void iniTabla(){ 
        Object[][] datos = {
            {"Nombre ", "Activo ", ""},
            {"", "", ""},};
        
        Object[] headernames = {"Nombre","Activo","Eliminar"};
        ModeloTabla modelo = new ModeloTabla(datos, headernames);
        tableCriteriosEvaluacion.setModel(modelo);
        
        tableCriteriosEvaluacion.setRowHeight(40);
        tableCriteriosEvaluacion.getColumnModel().getColumn(2).setCellRenderer(
                new ImagenCelda("/images/icons/trash.png"));
        
        tableCriteriosEvaluacion.addMouseListener(new MouseAdapter (){
            public void mouseClicked(MouseEvent e){
                super.mouseClicked(e);
                int renglon = tableCriteriosEvaluacion.rowAtPoint(e.getPoint());
                int columna = tableCriteriosEvaluacion.columnAtPoint(e.getPoint());
                
                JOptionPane.showMessageDialog(null, "Se eliminó registro en renglón: " + renglon);     
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitulo = new javax.swing.JPanel();
        lbllTitulo = new javax.swing.JLabel();
        panelCriteriosEvaluacion = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblActivo = new javax.swing.JLabel();
        chkActivo = new javax.swing.JCheckBox();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCriteriosEvaluacion = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        panelTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbllTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbllTitulo.setText("  Administración  Criterios de evaluación ");
        panelTitulo.add(lbllTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        getContentPane().add(panelTitulo, java.awt.BorderLayout.PAGE_START);

        panelCriteriosEvaluacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/backward.gif"))); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        panelCriteriosEvaluacion.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 130, 40));

        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Nombre");
        panelCriteriosEvaluacion.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 80, 30));

        lblActivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblActivo.setText("Activo");
        panelCriteriosEvaluacion.add(lblActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 80, 30));
        panelCriteriosEvaluacion.add(chkActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 20, 30));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/save.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelCriteriosEvaluacion.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 130, 40));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/update.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        panelCriteriosEvaluacion.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 153, 120, 40));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        panelCriteriosEvaluacion.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 410, 30));

        tableCriteriosEvaluacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableCriteriosEvaluacion);

        panelCriteriosEvaluacion.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 205, 800, 330));

        getContentPane().add(panelCriteriosEvaluacion, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // Guardará los datos insertados dentro de la tabla
        String message ="";
        
        if(txtNombre.getText().trim().isEmpty()){
            message = "El nombre debe tener un valor";
        }
        
        if(!message.isEmpty()){
            JOptionPane.showMessageDialog(this, message, "Guardar",
                JOptionPane.ERROR_MESSAGE);
            txtNombre.requestFocus();
            return;
        }
        

        this.iniTabla();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
// Modifica el campo de la columna seleccionada
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // Controlará el tamaño del texto ingresado en el cuadro de texto nombre
        if(txtNombre.getText().length() > 20){
            evt.consume();
        }
        // Controlará que no permita ingresar cualquier caracter pero números no
        char car = evt.getKeyChar();
        
        if(Character.isDigit(car)) {
            getToolkit().beep();          
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // Quitará pantalla actual y mostrará a la que está haciendo referencia
        this.setVisible(false);
        new ViewAdministracionCatalogo().setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAdministracionCriteriosEvaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAdministracionCriteriosEvaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAdministracionCriteriosEvaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAdministracionCriteriosEvaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /**
         * Para correr los componentes de la ventana
        */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {   
                    UIManager.setLookAndFeel("com.jtattoo.plaf.graphite.GraphiteLookAndFeel");  // Importará la utilería jtattoo para mostrar el estilo predeterminado para los componetes
                    new ViewAdministracionCriteriosEvaluacion().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ViewAdministracionCriteriosEvaluacion.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(ViewAdministracionCriteriosEvaluacion.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(ViewAdministracionCriteriosEvaluacion.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(ViewAdministracionCriteriosEvaluacion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JCheckBox chkActivo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblActivo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lbllTitulo;
    private javax.swing.JPanel panelCriteriosEvaluacion;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JTable tableCriteriosEvaluacion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
