/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import utils.UtileriasStyle;

/**
 *
 * Martha Guadalupe Rangel Alvarado GSI1333
 */
public class ViewAdminstracionCatalogo extends javax.swing.JFrame {

    /**
     * Esta clase contiene el menú para la administración de los cursos
     */
    public ViewAdminstracionCatalogo() {
        initComponents();
        //Es para mandar centrar la pantalla al momento de correr el proyecto
        UtileriasStyle.centrarVentana(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblTittle2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LstAdmonCatalogo = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblTittle2.setFont(new java.awt.Font("Arial Unicode MS", 2, 24)); // NOI18N
        LblTittle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTittle2.setText("Administración de catálogos");

        LstAdmonCatalogo.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Administración catálogos", "Criterio Evaluación", "Entidad", "Municipio", "Grupo", "Participante", "Materia" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        LstAdmonCatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LstAdmonCatalogoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(LstAdmonCatalogo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblTittle2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(438, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(LblTittle2)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LstAdmonCatalogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LstAdmonCatalogoMouseClicked
        int index = LstAdmonCatalogo.getSelectedIndex();
        if (index == 1) {
            new ViewAdministracionCriteriosEvaluacion().setVisible(true);
        } else if (index == 2) {
            new ViewEntidades().setVisible(true);
           
       
        } else if (index == 4) {
            new ViewGrupo().setVisible(true);

        } else if (index == 6) {
            new ViewAdministracionMaterias().setVisible(true);

        }


    }//GEN-LAST:event_LstAdmonCatalogoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    //Dentro de estas lineas de comando se le da formato al diseno 
                    UIManager.setLookAndFeel("com.jtattoo.plaf.graphite.GraphiteLookAndFeel");
                    new ViewAdminstracionCatalogo().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ViewAdminstracionCatalogo.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(ViewAdminstracionCatalogo.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(ViewAdminstracionCatalogo.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(ViewAdminstracionCatalogo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblTittle2;
    private javax.swing.JList LstAdmonCatalogo;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
