/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import utils.UtileriasStyle;

/**
 * Descripcion: Formulario donde se puede cambiar una contraseña
 *
 * @author Daniel Aguilar dhaniel212@gmail.com GSI-1333
 */
public class ViewGrupo extends javax.swing.JFrame {

    /**
     * Creates new form ViewPassword
     */
    public ViewGrupo() {
        initComponents();
        //Linea de codigo que entra a las utilerias de estilos, manda llamar el metodo centrarVentana
        UtileriasStyle.centrarVentana(this);
        //Despe el paquete de utilerias de estilos aplica un nuevo estilo al panel deseado
        UtileriasStyle.initStyle(PanelContenido.getComponents());
        UtileriasStyle.initStyle(PanelCajas.getComponents());
        UtileriasStyle.initStyle(panelBoton.getComponents());

    }

    private void validaCombo() {

        String message = "";
        if (cboTurno.getSelectedItem().equals("Selecciona Turno")) {
            message = "Elige una opcion del campo 'Turno'.\n";

        }
        if (cboCarrera.getSelectedItem().equals("Selecciona Carrera")) {
            message = "Elige una opcion del campo 'Carrera'.\n";

        }
        if (cboCurso.getSelectedItem().equals("Selecciona Curso")) {
            message = "Elige una opcion del campo 'Curso'.\n";

        }
        if (!message.isEmpty()) {
            JOptionPane.showMessageDialog(this, message, "Entrada al Sistema",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void validaCaja() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo1 = new javax.swing.JLabel();
        PanelContenido = new javax.swing.JPanel();
        PanelCajas = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cboTurno = new javax.swing.JComboBox<>();
        lblCarrera = new javax.swing.JLabel();
        cboCarrera = new javax.swing.JComboBox<>();
        lblCurso = new javax.swing.JLabel();
        cboCurso = new javax.swing.JComboBox<>();
        lblEstado = new javax.swing.JLabel();
        chkEstado = new javax.swing.JCheckBox();
        panelBoton = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JToggleButton();
        btnCancelar = new javax.swing.JToggleButton();
        btnParticipantes = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 600));

        lblTitulo1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo1.setText("Administración de Grupo");
        getContentPane().add(lblTitulo1, java.awt.BorderLayout.PAGE_START);

        PanelContenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelCajas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelCajas.setLayout(new java.awt.GridLayout(7, 2));

        lblNombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNombre.setText("Nombre");
        PanelCajas.add(lblNombre);
        PanelCajas.add(txtNombre);

        lblDescripcion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDescripcion.setText("Descripción");
        PanelCajas.add(lblDescripcion);

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        PanelCajas.add(jScrollPane1);

        lblCodigo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCodigo.setText("Código");
        PanelCajas.add(lblCodigo);
        PanelCajas.add(txtCodigo);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Turno");
        PanelCajas.add(jLabel2);

        cboTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona Turno", "MATUTINO", "VESPERTINO", " " }));
        PanelCajas.add(cboTurno);

        lblCarrera.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCarrera.setText("Carrera");
        PanelCajas.add(lblCarrera);

        cboCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona Carrera", "Diseño Digital", "Multimedia y Comercio Electornico", "Redes y Telecomunicaciones", "Sistemas Informaticos" }));
        PanelCajas.add(cboCarrera);

        lblCurso.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCurso.setText("Curso");
        PanelCajas.add(lblCurso);

        cboCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona Curso", "Dase de Datos", "Desarrollo de Aplicaciones 1", "Desarrollo de Aplicaciones Web", " " }));
        PanelCajas.add(cboCurso);

        lblEstado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEstado.setText("Estado");
        PanelCajas.add(lblEstado);
        PanelCajas.add(chkEstado);

        PanelContenido.add(PanelCajas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 580, 510));

        panelBoton.setLayout(new java.awt.GridLayout(2, 2));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        panelBoton.add(btnAgregar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelBoton.add(btnCancelar);

        btnParticipantes.setText("Participantes");
        btnParticipantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParticipantesActionPerformed(evt);
            }
        });
        panelBoton.add(btnParticipantes);

        PanelContenido.add(panelBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 200, 110));

        getContentPane().add(PanelContenido, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        String message = "";
        validaCombo();
        if (txtNombre.getText().trim().isEmpty()) {
            message = "Inserta datos el campo 'Nombre'.\n";
        }
        if (txtDescripcion.getText().trim().isEmpty()) {
            message = "Agrega una descripción \n en el campo correspontiente.\n";
        }
        if (txtCodigo.getText().trim().isEmpty()) {
            message = "Inserta datos el el campo 'Código'.\n";
        }
        if (!chkEstado.isSelected()) {
            message = "Verifique el estado se correcto.\n";
        }
        if (!message.isEmpty()) {
            JOptionPane.showMessageDialog(this, message, "Entrada al Sistema",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnParticipantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParticipantesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ViewAdministracionParticipanteDocente().setVisble(true);

    }//GEN-LAST:event_btnParticipantesActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        txtNombre.setText(null);
        txtDescripcion.setText(null);
        txtCodigo.setText(null);
        cboTurno.setSelectedItem("Selecciona Turno");
        cboCarrera.setSelectedItem("Selecciona Carrera");
        cboCurso.setSelectedItem("Selecciona Curso");
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //Se embuelve el bloque de codigo try catch

                new ViewGrupo().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCajas;
    private javax.swing.JPanel PanelContenido;
    private javax.swing.JToggleButton btnAgregar;
    private javax.swing.JToggleButton btnCancelar;
    private javax.swing.JToggleButton btnParticipantes;
    private javax.swing.JComboBox<String> cboCarrera;
    private javax.swing.JComboBox<String> cboCurso;
    private javax.swing.JComboBox<String> cboTurno;
    private javax.swing.JCheckBox chkEstado;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JPanel panelBoton;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
