/*
 * Esta pantalla es la pantalla principal para la administración de cursos
 */
package views;
//Estamos importando las librerias necesarias
import java.awt.Event;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import utils.UtileriasStyle;


/**
 *
 * @Martha Guadalupe Rangel Alvarado
 * Pantalla Realizada: Pantalla principal de Estudiante
 * Grupo GSI1313
 * Fecha de eleboracion: 10 de Julio de 2017
 */
public class ViewPrincipalDocente extends javax.swing.JFrame {
    

    /**
     * Creates new form Principal
     */
    public ViewPrincipalDocente() {
        initComponents();
        //Es para mandar centrar la pantalla al momento de correr el proyecto
        UtileriasStyle.centrarVentana(this);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        lblBienvenido = new javax.swing.JLabel();
        mnuPrincipal = new javax.swing.JMenuBar();
        mnuMisCursos = new javax.swing.JMenu();
        mnuRegistroCursos = new javax.swing.JMenu();
        mnuCambiarContrasena = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        lblBienvenido.setFont(new java.awt.Font("Bodoni MT Condensed", 2, 36)); // NOI18N
        lblBienvenido.setText("Bienvenido");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(lblBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBienvenido)
                .addContainerGap(546, Short.MAX_VALUE))
        );

        mnuPrincipal.setPreferredSize(new java.awt.Dimension(306, 36));

        mnuMisCursos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 0), null, null));
        mnuMisCursos.setText("Mis Cursos");
        mnuMisCursos.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        mnuMisCursos.setOpaque(true);
        mnuMisCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuMisCursosMouseClicked(evt);
            }
        });
        mnuMisCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMisCursosActionPerformed(evt);
            }
        });
        mnuPrincipal.add(mnuMisCursos);

        mnuRegistroCursos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 0), null, null));
        mnuRegistroCursos.setText("Nuevo Curso");
        mnuRegistroCursos.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        mnuRegistroCursos.setOpaque(true);
        mnuRegistroCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuRegistroCursosMouseClicked(evt);
            }
        });
        mnuPrincipal.add(mnuRegistroCursos);

        mnuCambiarContrasena.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 0), null, null));
        mnuCambiarContrasena.setText("Administración ");
        mnuCambiarContrasena.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        mnuCambiarContrasena.setOpaque(true);
        mnuCambiarContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuCambiarContrasenaMouseClicked(evt);
            }
        });
        mnuPrincipal.add(mnuCambiarContrasena);

        setJMenuBar(mnuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    private void mnuMisCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMisCursosActionPerformed
       
    }//GEN-LAST:event_mnuMisCursosActionPerformed

    private void mnuMisCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuMisCursosMouseClicked
      JButton boton = new JButton("Desarrollo de aplicaciones I");
    boton.setVisible(true);
    boton.setSize(200,150);
    boton.setLocation (150, 150);
    JButton boton2 = new JButton("Programación");
    boton2.setVisible(true);
    boton2.setSize(200,150);
    boton2.setLocation (450, 150);
    jPanel1.add(boton);
    jPanel1.add(boton2);
   boton.addActionListener(new ActionListener() {

          @Override
          public void actionPerformed(ActionEvent ae) {
              
                new ViewAdminstracionCurso().setVisible(true);
             //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
          
          
          }
          });
   
    }//GEN-LAST:event_mnuMisCursosMouseClicked



    

    
       
    private void mnuRegistroCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuRegistroCursosMouseClicked
      new ViewRegistroCurso().setVisible(true);
    }//GEN-LAST:event_mnuRegistroCursosMouseClicked

   

    private void mnuCambiarContrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuCambiarContrasenaMouseClicked
        new ViewAdminstracionCatalogo().setVisible(true);
    }//GEN-LAST:event_mnuCambiarContrasenaMouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipalDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipalDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipalDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipalDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    //Dentro de estas lineas de comando se le da formato al diseno 
                    UIManager.setLookAndFeel("com.jtattoo.plaf.graphite.GraphiteLookAndFeel");
                    new ViewPrincipalDocente().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ViewPrincipalDocente.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(ViewPrincipalDocente.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(ViewPrincipalDocente.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(ViewPrincipalDocente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JMenu mnuCambiarContrasena;
    private javax.swing.JMenu mnuMisCursos;
    private javax.swing.JMenuBar mnuPrincipal;
    private javax.swing.JMenu mnuRegistroCursos;
    // End of variables declaration//GEN-END:variables
}
