package views;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import utils.UtileriasStyle;

/**
 * Descripción Interfaz: RF23 Administración de unidades temáticas.
 *
 * @author Ana Lucia Vazquez Ramirez
 * @author lvazquez GSI1333
 */
public class ViewUnidadesTematicas extends javax.swing.JFrame {

    //Encabezado de las columnas
    private String[] encabezadoColumnas = {"Nombre", "Horas Teóricas", "Horas Prácticas", "Duración", "Eliminar"};//Definiendo el nombre de las columnas
    //Definiendo el modelo
    private DefaultTableModel model = new DefaultTableModel(null, encabezadoColumnas);

    /**
     * Creates new form ViewAdministrador
     */
    public ViewUnidadesTematicas() {
        initComponents();
        UtileriasStyle.centrarVentana(this);//centra la ventana en cualquier resolución 
        UtileriasStyle.initStyle(panelContacto.getComponents());//le da formato a el panel 
        // UtileriasStyle.initStyle(panelRegresar.getComponents());
        UtileriasStyle.initStyle(panelTitulo.getComponents());//le da formato a el panel 
        tableAdministrador.setModel(model); //invocando la tabla 
        this.initComboHrsPracticas();  //Se llama al metodo
        this.initComboDuracion();
        this.initComboHorasTeoricas();

    }

    private void initComboHrsPracticas() {
        chkHorasPracticas.removeAllItems();///Elimina todo el combo
        for (int i = 0; i <= 40; i++) {
            chkHorasPracticas.addItem(Integer.toString(i));
        }
    }

    private void initComboDuracion() {
        chkDuracion.removeAllItems();///Elimina todo el combo
        for (int i = 0; i <= 40; i++) {
            chkDuracion.addItem(Integer.toString(i));
        }
    }

    private void initComboHorasTeoricas() {
        chkHorasTeoricas.removeAllItems();///Elimina todo el combo
        for (int i = 0; i <= 40; i++) {
            chkHorasTeoricas.addItem(Integer.toString(i));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panelRegresar = new javax.swing.JPanel();
        panelContacto = new javax.swing.JPanel();
        lblMateria = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblObjetivo = new javax.swing.JLabel();
        lblDuracion = new javax.swing.JLabel();
        lblHorasTeorias = new javax.swing.JLabel();
        lblHorasPracticas = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnTemas = new javax.swing.JButton();
        chkDesarrollo = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObjetivo = new javax.swing.JTextArea();
        chkDuracion = new javax.swing.JComboBox<>();
        chkHorasTeoricas = new javax.swing.JComboBox<>();
        chkHorasPracticas = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableAdministrador = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 600));

        panelTitulo.setLayout(new javax.swing.BoxLayout(panelTitulo, javax.swing.BoxLayout.LINE_AXIS));

        lblTitulo.setText("Registro de Unidades Temáticas");
        panelTitulo.add(lblTitulo);

        getContentPane().add(panelTitulo, java.awt.BorderLayout.PAGE_START);

        panelRegresar.setLayout(new javax.swing.BoxLayout(panelRegresar, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(panelRegresar, java.awt.BorderLayout.LINE_END);

        lblMateria.setText("Materia");

        lblNombre.setText("Nombre");

        lblDescripcion.setText("Descripción");

        lblObjetivo.setText("Objetivo");

        lblDuracion.setText("Duración");

        lblHorasTeorias.setText("Horas Teóricas");

        lblHorasPracticas.setText("Horas Prácticas");

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Agregar.jpg"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modificar.png"))); // NOI18N
        btnModificar.setText("Modificar");

        btnTemas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Biblioteca.png"))); // NOI18N
        btnTemas.setText("Temas");
        btnTemas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTemasMouseClicked(evt);
            }
        });

        chkDesarrollo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desarrollo de aplicaciones I" }));

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        txtObjetivo.setColumns(20);
        txtObjetivo.setRows(5);
        jScrollPane2.setViewportView(txtObjetivo);

        chkDuracion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0" }));

        chkHorasTeoricas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0" }));

        chkHorasPracticas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0" }));
        chkHorasPracticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkHorasPracticasActionPerformed(evt);
            }
        });

        tableAdministrador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tableAdministrador);

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FLECHA.png"))); // NOI18N
        btnRegresar.setText("Regresar");

        javax.swing.GroupLayout panelContactoLayout = new javax.swing.GroupLayout(panelContacto);
        panelContacto.setLayout(panelContactoLayout);
        panelContactoLayout.setHorizontalGroup(
            panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContactoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelContactoLayout.createSequentialGroup()
                        .addComponent(lblHorasPracticas)
                        .addGap(18, 18, 18)
                        .addComponent(chkHorasPracticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelContactoLayout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addGap(33, 33, 33)
                        .addComponent(btnModificar)
                        .addGap(32, 32, 32)
                        .addComponent(btnTemas)))
                .addGap(88, 88, 88))
            .addGroup(panelContactoLayout.createSequentialGroup()
                .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelContactoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDuracion)
                        .addGap(18, 18, 18)
                        .addComponent(chkDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(lblHorasTeorias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkHorasTeoricas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelContactoLayout.createSequentialGroup()
                        .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblObjetivo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(77, 77, 77)
                        .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(btnRegresar))
            .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContactoLayout.createSequentialGroup()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 86, Short.MAX_VALUE)))
        );
        panelContactoLayout.setVerticalGroup(
            panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContactoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMateria)
                    .addComponent(chkDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresar))
                .addGap(24, 24, 24)
                .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescripcion)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblObjetivo)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHorasTeorias)
                        .addComponent(chkHorasTeoricas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDuracion)
                        .addComponent(lblHorasPracticas)
                        .addComponent(chkDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chkHorasPracticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnTemas)
                    .addComponent(btnModificar))
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContactoLayout.createSequentialGroup()
                    .addContainerGap(364, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(32, Short.MAX_VALUE)))
        );

        getContentPane().add(panelContacto, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        // TODO add your handling code here:

        String message = "";
        if (txtNombre.getText().trim().isEmpty()) {
            message = "Debe ingresar un nombre .\n";
        }
        if (txtDescripcion.getText().trim().isEmpty()) {
            message = "Debe ingresar una descripcion .\n";
        }
        if (txtObjetivo.getText().trim().isEmpty()) {
            message = "Debe ingresar un objetivo .\n";
        }
        if (!message.isEmpty()) {
            JOptionPane.showMessageDialog(this, message, "Ingresos de datos", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnAgregarMouseClicked

    private void chkHorasPracticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkHorasPracticasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkHorasPracticasActionPerformed

    private void btnTemasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTemasMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new viewTemas().setVisible(true);
    }//GEN-LAST:event_btnTemasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewUnidadesTematicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewUnidadesTematicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewUnidadesTematicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewUnidadesTematicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel("com.jtattoo.plaf.graphite.GraphiteLookAndFeel");//para darle formato a el diseño 
                    new ViewUnidadesTematicas().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ViewUnidadesTematicas.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(ViewUnidadesTematicas.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(ViewUnidadesTematicas.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(ViewUnidadesTematicas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnTemas;
    private javax.swing.JComboBox<String> chkDesarrollo;
    private javax.swing.JComboBox<String> chkDuracion;
    private javax.swing.JComboBox<String> chkHorasPracticas;
    private javax.swing.JComboBox<String> chkHorasTeoricas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblHorasPracticas;
    private javax.swing.JLabel lblHorasTeorias;
    private javax.swing.JLabel lblMateria;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblObjetivo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelContacto;
    private javax.swing.JPanel panelRegresar;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JTable tableAdministrador;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtObjetivo;
    // End of variables declaration//GEN-END:variables
}
