/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.table.DefaultTableModel;
import utils.UtileriasStyle;

/**
 * Descripcion: Interfaz para la impresión de la planeación del curso.
 *
 * @author Andrés Tapia Tapia
 * @author JB Tapia
 */
public class ViewImprimirPlaneacion extends javax.swing.JFrame {

    //Encabezado de las columnas
    private String[] encabezadoColumnas = {"Momento", "Actividad", "Descripción", "Instrumento Eval.", "Producto Aprendizaje", "Ponderación"};
    //Definiendo el modelo
    private DefaultTableModel modelo = new DefaultTableModel(null, encabezadoColumnas);

    /**
     * Creates new form ViewS
     */
    public ViewImprimirPlaneacion() {
        initComponents();
        tableContenido.setModel(modelo);//Se llama a la tabla
        UtileriasStyle.centrarVentana(this);
        UtileriasStyle.initStyle(panelCentral.getComponents());//Se le da formato al panel
        UtileriasStyle.initStyle(tableContenido.getComponents());//Se le da formato al panel
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCentral = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableContenido = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Imprimir Planeación del Curso");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        panelCentral.setPreferredSize(new java.awt.Dimension(800, 600));
        panelCentral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        labelTitulo.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(51, 51, 255));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Nombre del curso");
        panelCentral.add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 60));

        tableContenido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tableContenido);

        panelCentral.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 790, 460));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backward_nav.gif"))); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        panelCentral.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 530, 110, -1));

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print_edit.png"))); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        panelCentral.add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 530, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:                
        new ViewPlaneacionCurso().setVisible(true);//Hace visible la pantalla de planeacion del curso
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JTable tableContenido;
    // End of variables declaration//GEN-END:variables
}
